services:
  - type: web
    name: ultraship-empmgt-backend
    healthCheckPath: /actuator/health
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ultraship-empmgt-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: production

databases:
  - name: ultraship-empmgt-db
    databaseName: employee_db