spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate # Important: use validate instead of update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    repair-on-migrate: true
  graphql:
    graphiql:
      enabled: true
    path: /graphql

app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 3600000 # 1 hour
    refresh-expiration: 604800000 # 7 days

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.example.employeemanagement: DEBUG
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health