spring:
  datasource:
    url: ${DATABASE_URL}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DATABASE_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    com.example.employeemanagement: INFO
    org.springframework.security: WARN
    org.flywaydb.core.internal.database: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health